name: atonline_login
description: Client-side login page for applications using AtOnline apis and custom realms
version: 0.2.1
homepage: https://github.com/AtOnline/atonline-flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  material_design_icons_flutter: ^3.4.4795
  crypto: ^2.1.3
  url_launcher: ^5.4.1 # flutter team
  image_picker: ^0.6.3 # flutter team
  atonline_api: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
