name: atonline_login
description: Client-side login page for applications using AtOnline apis and custom realms
version: 0.3.5
homepage: https://github.com/AtOnline/atonline-flutter

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.0
  url_launcher: ^6.0.2 # flutter team
  image_picker: ^0.6.0 # flutter team
  atonline_api: ^0.3.0
  flutter_svg: ^0.19.3
  flutter_web_auth: ^0.2.4 # non official

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
